services:
  app:
    build: .
    ports:
      - "3001:3001"
    env_file:
      - .env
    depends_on:
      - database
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  database:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - redis-data:/data

volumes:
  postgres_data:
  redis-data:
